--416  
--Pulls CE for all individuals on a HH day; by HH purchase or not, and during HH time or not

WITH SR AS (
  SELECT DISTINCT
  sr.GUID_USER_ID
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,TRUNC(sr.TRANS_DTM) AS SURVEY_TRANS_DATE
  ,item.IS_GV_ESP
  ,item.IS_GV_LM
  ,item.IS_G_FRAPP
  ,item.IS_GV_FRAPP
  ,item.IS_GV_FRAPP_ESP
  ,item.IS_GV_ESP_COLD
  ,item.IS_RFRSHR_ICTEA_LEM
  ,(CASE WHEN TRUNC(sr.TRANS_DTM) IN ('24-MAY-18','06-JUL-18') AND item.IS_GV_ESP = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) IN ('24-MAY-18','06-JUL-18') AND item.IS_GV_ESP = 0 THEN 'NON-HHITEM' 
            WHEN TRUNC(sr.TRANS_DTM) = '07-JUN-18' AND item.IS_GV_LM = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) = '07-JUN-18' AND item.IS_GV_LM = 0 THEN 'NON-HHITEM' 
            WHEN TRUNC(sr.TRANS_DTM) IN ('15-JUN-18','10-AUG-18') AND item.IS_G_FRAPP = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) IN ('15-JUN-18','10-AUG-18') AND item.IS_G_FRAPP = 0 THEN 'NON-HHITEM' 
            WHEN TRUNC(sr.TRANS_DTM) IN ('21-JUN-18','19-JUL-18','02-AUG-18') AND item.IS_GV_FRAPP = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) IN ('21-JUN-18','19-JUL-18','02-AUG-18') AND item.IS_GV_FRAPP = 0 THEN 'NON-HHITEM' 
            WHEN TRUNC(sr.TRANS_DTM) = '29-JUN-18' AND item.IS_GV_FRAPP_ESP = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) = '29-JUN-18' AND item.IS_GV_FRAPP_ESP = 0 THEN 'NON-HHITEM' 
            WHEN TRUNC(sr.TRANS_DTM) = '12-JUL-18' AND item.IS_GV_ESP_COLD = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) = '12-JUL-18' AND item.IS_GV_ESP_COLD = 0 THEN 'NON-HHITEM' 
            WHEN TRUNC(sr.TRANS_DTM) = '26-JUL-18' AND item.IS_RFRSHR_ICTEA_LEM = 1 THEN 'HHITEM' 
      WHEN  TRUNC(sr.TRANS_DTM) = '26-JUL-18' AND item.IS_RFRSHR_ICTEA_LEM = 0 THEN 'NON-HHITEM' 
      ELSE NULL END) AS HH_ITEM
  ,TO_CHAR(sr.TRANS_DTM, 'HH24') AS DAY_HOUR
  ,(CASE WHEN TO_CHAR(sr.TRANS_DTM, 'HH24') < 15 THEN 'AM' WHEN TO_CHAR(sr.TRANS_DTM, 'HH24') >= 15 THEN 'PM' ELSE NULL END) AS DAY_PART

FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

LEFT JOIN APPOTHER.CUST_INS_WEIGHTS w
  ON sr.CASE_ID = w.CASE_ID

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)

JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'

JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    AND pi.BUS_DT IN ('24-MAY-18', '07-JUN-18', '15-JUN-18', '21-JUN-18', '29-JUN-18', '06-JUL-18', '12-JUL-18', '19-JUL-18', '26-JUL-18', '02-AUG-18', '10-AUG-18')

LEFT JOIN (SELECT ITEM_ID
  ,SUM(CASE WHEN dept_descr='ESPRESSO BEVERAGES' and pkg_sz_qty in ('VENTI',' GRANDE') THEN 1 ELSE 0 END) AS IS_GV_ESP
  ,SUM(CASE WHEN dept_descr='ESPRESSO BEVERAGES' and sub_dept_descr='ESPRESSO BEVERAGES' and prod_type_descr in('LATTE','MACCHIATO') and pkg_sz_qty in ('VENTI',' GRANDE') THEN 1 ELSE 0 END) AS IS_GV_LM
  ,SUM(CASE WHEN sub_dept_descr in ('FRAPPUCCINO BLENDED COFFE','FRAPPUCCINO BLENDED CREME','FRAPPUCCINO BLENDED LIGHT') and pkg_sz_qty in ('GRANDE') THEN 1 ELSE 0 END) AS IS_G_FRAPP
  ,SUM(CASE WHEN sub_dept_descr in ('FRAPPUCCINO BLENDED COFFE','FRAPPUCCINO BLENDED CREME','FRAPPUCCINO BLENDED LIGHT') and pkg_sz_qty in ('VENTI','GRANDE') THEN 1 ELSE 0 END) AS IS_GV_FRAPP
  ,SUM(CASE WHEN sub_dept_descr in ('ESPRESSO BEVERAGES','FRAPPUCCINO BLENDED COFFE','FRAPPUCCINO BLENDED CREME','FRAPPUCCINO BLENDED LIGHT') and pkg_sz_qty in ('VENTI','GRANDE') THEN 1 ELSE 0 END) AS IS_GV_FRAPP_ESP
  ,SUM(CASE WHEN dept_descr IN ('ESPRESSO BEVERAGES','BREWED COFFEE') AND sub_dept_descr IN ('ICED COFFEE') and pkg_sz_qty in ('VENTI',' GRANDE') THEN 1 ELSE 0 END) AS IS_GV_ESP_COLD
  ,SUM(CASE WHEN SUB_DEPT_DESCR IN ('REFRESHERS','TEA LEMONADE','ICED TEA - SHAKEN TEA') AND pkg_sz_qty IN ('VENTI',' GRANDE','TRENTA') THEN 1 ELSE 0 END) AS IS_RFRSHR_ICTEA_LEM
  FROM appca.d_item
  GROUP BY ITEM_ID) item
ON pi.ITEM_ID = item.ITEM_ID
 
WHERE sr.QSTN_ID IN ('Q2_2','Q2_1','Q2_3','Q2_4','Q2_5','Q2_6','Q2_7')
  AND sr.RSPNS_ID <> '9'
  AND ca.FSCL_YR_NUM = 2018 
  AND ca.CAL_DT IN ('24-MAY-18', '07-JUN-18', '15-JUN-18', '21-JUN-18', '29-JUN-18', '06-JUL-18', '12-JUL-18', '19-JUL-18', '26-JUL-18', '02-AUG-18', '10-AUG-18')

GROUP BY
  sr.GUID_USER_ID
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,item.IS_GV_ESP
  ,item.IS_GV_LM
  ,item.IS_G_FRAPP
  ,item.IS_GV_FRAPP
  ,item.IS_GV_FRAPP_ESP
  ,item.IS_GV_ESP_COLD
  ,item.IS_RFRSHR_ICTEA_LEM
  ,TO_CHAR(sr.TRANS_DTM, 'HH24') 
  ,TRUNC(sr.TRANS_DTM)
) SELECT
  SR.QSTN_ID
  ,SUM(CASE WHEN SR.RSPNS_ID = '7' THEN 1 ELSE 0 END) AS TOTAL_TB
  ,COUNT(*) AS TOTAL_RESP
  ,ROUND(SUM(CASE WHEN SR.RSPNS_ID = '7' THEN 1 ELSE 0 END) / COUNT(*),4) AS TB_SCORE
  ,ROUND(STDDEV(CASE WHEN SR.RSPNS_ID = '7' THEN 1 ELSE 0 END),4) AS TB_SCORE_SD
  ,SR.HH_ITEM
  ,SR.DAY_PART
  
  FROM SR
  
  GROUP BY 
  SR.QSTN_ID
  ,SR.HH_ITEM
  ,SR.DAY_PART

--TO SEARCH FOR NEW HH ITEM CODES
/*
SELECT DEPT_DESCR, SUB_DEPT_DESCR, prod_type_descr, COUNT(*)
FROM appca.d_item 
WHERE pkg_sz_qty in ('GRANDE')
GROUP BY DEPT_DESCR, SUB_DEPT_DESCR, prod_type_descr
ORDER BY SUB_DEPT_DESCR, prod_type_descr
*/


