--416  
--Pulls GUIDs for all individuals on a HH day; by HH purchase or not, and during HH time or not, plus pre-30D number of visits

WITH SR AS (
  SELECT DISTINCT
  sr.GUID_USER_ID
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,TRUNC(sr.TRANS_DTM) AS SURVEY_TRANS_DATE
  ,(CASE WHEN item.IS_GVE = 1 THEN 'HHITEM' ELSE 'NON-HHITEM' END) AS HH_ITEM
  ,TO_CHAR(sr.TRANS_DTM, 'HH24') AS DAY_HOUR
  ,(CASE WHEN TO_CHAR(sr.TRANS_DTM, 'HH24') < 15 THEN 'AM'
        WHEN TO_CHAR(sr.TRANS_DTM, 'HH24') >= 15 THEN 'PM'
        ELSE NULL END) AS DAY_PART

FROM APPOTHER.AFT_CV_SRVY_RSPNS sr

LEFT JOIN APPOTHER.CUST_INS_WEIGHTS w
  ON sr.CASE_ID = w.CASE_ID

JOIN APPCA.D_CAL ca
  ON ca.CAL_DT = TRUNC(sr.TRANS_DTM)

JOIN APPCA.D_STORE_VERS st
  ON sr.STORE_NUM = st.STORE_NUM
    AND st.CURRENT_FLG = 'Y'
    AND st.OWNR_TYPE_CD = 'CO'
    AND st.CNTRY_CD_2_DGT_ISO = 'US'

JOIN APPCA.F_POS_LINE_ITEM pi
  ON TO_CHAR(sr.TRANS_DTM, 'YYYYMMDD') || TRIM(TO_CHAR(sr.STORE_NUM, '000000'))
      || TRIM(TO_CHAR(SUBSTR(sr.RGSTR_NUM, -1, 2),'00')) || sr.TRANS_ID = pi.TRANS_ID
    AND pi.CNTRY_CD = 'US'
    AND pi.BUS_DT = '24-MAY-18' 

LEFT JOIN (SELECT ITEM_ID
  ,SUM(CASE WHEN dept_descr='ESPRESSO BEVERAGES' and pkg_sz_qty in ('VENTI',' GRANDE') THEN 1 ELSE 0 END) AS IS_GVE
  FROM appca.d_item
  GROUP BY ITEM_ID) item
ON pi.ITEM_ID = item.ITEM_ID

WHERE sr.QSTN_ID IN ('Q2_2')
  AND sr.RSPNS_ID <> '9'
  --AND sr.STORE_NUM = 5798
  AND ca.FSCL_YR_NUM = 2018 
  AND ca.FSCL_WK_IN_YR_NUM = 34 -- MAY 24 -- CASE WHEN dept_descr='ESPRESSO BEVERAGES' and pkg_sz_qty in ('VENTI',' GRANDE') THEN 1 ELSE 0 END

GROUP BY
  sr.GUID_USER_ID
  ,sr.QSTN_ID
  ,sr.RSPNS_ID
  ,ca.FSCL_YR_NUM
  ,ca.FSCL_WK_IN_YR_NUM
  ,item.IS_GVE
  ,TO_CHAR(sr.TRANS_DTM, 'HH24') 
  ,TRUNC(sr.TRANS_DTM)
  ),
SR2 AS (
    SELECT SR.GUID_USER_ID,
      SR.HH_ITEM,
      SR.DAY_PART,
      SR.FSCL_WK_IN_YR_NUM,
      SR.SURVEY_TRANS_DATE,
      SR.QSTN_ID,
      SR.RSPNS_ID,
      CASE WHEN SR.RSPNS_ID = '7' THEN 1 ELSE 0 END AS TOTAL_TB

      --SUM(CASE WHEN POS1.BUS_DT > TRUNC(SR.SURVEY_TRANS_DATE) THEN POS1.GROSS_REV_LCL_AMT ELSE NULL END) AS SPEND_POST60D,
      COUNT(DISTINCT CASE WHEN POS1.BUS_DT < TRUNC(SR.SURVEY_TRANS_DATE) THEN POS1.TRANS_ID ELSE NULL END) AS VISITS_PRE30D

    FROM SR
      LEFT OUTER JOIN APPCA.F_POS_HDR POS1
      ON SR.GUID_USER_ID = POS1.GUID_ID
        AND POS1.BUS_DT >= TRUNC(SR.SURVEY_TRANS_DATE)- INTERVAL'30'DAY 
      
      GROUP BY SR.GUID_USER_ID,
      SR.HH_ITEM,
      SR.DAY_PART,
      SR.FSCL_WK_IN_YR_NUM,
      SR.SURVEY_TRANS_DATE,
      SR.QSTN_ID,
      SR.RSPNS_ID
) SELECT
  SR2.QSTN_ID
  ,SUM(TOTAL_TB) AS TOTAL_TB
  ,COUNT(*) AS TOTAL_RESP
  ,ROUND(SUM(TOTAL_TB) / COUNT(*),4) AS CC_SCORE
  ,ROUND(STDDEV(TOTAL_TB),4) AS CC_SCORE_SD
  ,ROUND(AVG(SR2.VISITS_PRE30D),2) AS VISITS_PRE30D_AVG
  ,ROUND(STDDEV(SR2.VISITS_PRE30D),2) AS VISITS_PRE30D_SD
  ,SR2.HH_ITEM
  ,SR2.DAY_PART
  ,SR2.FSCL_WK_IN_YR_NUM
  
  FROM SR2
  
  GROUP BY 
  SR2.QSTN_ID
  ,SR2.HH_ITEM
  ,SR2.DAY_PART
  ,SR2.FSCL_WK_IN_YR_NUM